# Generated by Django 3.2.3 on 2021-05-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20210528_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyect',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Dirección web'),
        ),
    ]
